FROM node:alpine

WORKDIR /usr/src/server

COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./prisma ./prisma

RUN yarn install

COPY . ./

RUN npx prisma generate

ENV NODE_ENV=development

EXPOSE 5000

CMD ["yarn","run","dev"]