name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-deploy-server:
    name: Build and Deploy server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cyator/yf-dev-server
          registry: docker.io
          directory: ./
          dockerfile: ./Dockerfile.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

